
import { AIProvider, AIRequestParams, Suggestion, SupportedLanguage, CognitiveProfile, MemoryEntry, MemoryScope } from '../types';
import { geminiProviderInstance } from './geminiService';
import { audit } from './auditLog';

/**
 * Deterministic fallback provider for basic interactions when cloud APIs fail.
 */
class LocalFallbackProvider implements AIProvider {
  public readonly id = 'osai-local-shield';
  public readonly name = 'OSAI Local Guard';

  public async getSuggestion(params: AIRequestParams): Promise<Suggestion | null> {
    const { context } = params;
    
    if (context.toLowerCase().includes('osai')) {
      return {
        id: 'local-' + Date.now(),
        context,
        action: 'GREET',
        description: 'Desculpe, estou operando em modo offline limitado, mas estou aqui para ajudar.',
        riskLevel: 'LOW',
        type: 'system',
        intent: 'SYSTEM',
        blockType: 'TEXT',
        criticality: 'LOW',
        reasoning: 'Cloud provider failure detected. Falling back to local greeting.',
        isSuggestion: false,
        providerId: this.id
      };
    }

    return null;
  }
}

const MODE_GREETINGS: Record<CognitiveProfile, Record<SupportedLanguage, string>> = {
  [CognitiveProfile.NORMAL]: {
    'pt-BR': 'O OSAI está ouvindo. O que você precisa?',
    'en-US': 'OSAI is listening. What do you need?',
    'es-ES': 'OSAI está ouvindo. ¿Qué necesitas?',
    'fr-FR': 'OSAI est à l\'écoute. De quoi avez-vous besoin ?',
    'de-DE': 'OSAI hört zu. Was benötigen Sie?',
    'it-IT': 'OSAI è in ascolto. Di cosa hai bisogno?',
    'zh-CN': 'OSAI正在聆听。你需要什么？',
    'ja-JP': 'OSAIが聞いています。何が必要ですか？'
  },
  [CognitiveProfile.ACTIVE]: {
    'pt-BR': 'OSAI ativo. Como posso te ajudar agora?',
    'en-US': 'OSAI active. How can I help you now?',
    'es-ES': 'OSAI activo. ¿Como posso ayudarte ahora?',
    'fr-FR': 'OSAI actif. Comment puis-je vous aider maintenant ?',
    'de-DE': 'OSAI aktiv. Wie kann ich Ihnen agora helfen?',
    'it-IT': 'OSAI attivo. Come posso aiutarti ora?',
    'zh-CN': 'OSAI已激活。我现在该如何帮助你？',
    'ja-JP': 'OSAIアクティブ。今、どのようにお手伝いできますか？'
  },
  [CognitiveProfile.CRITICAL]: {
    'pt-BR': 'OSAI em prontidão total. Diga o que você precisa.',
    'en-US': 'OSAI in full readiness. Tell me what you need.',
    'es-ES': 'OSAI en alerta total. Dime qué necesitas.',
    'fr-FR': 'OSAI en alerte totale. Dites-moi ce dont você precisa.',
    'de-DE': 'OSAI in voller Bereitschaft. Sagen Sie mir, was Sie brauchen.',
    'it-IT': 'OSAI in piena prontezza. Dimmi di cosa hai bisogno.',
    'zh-CN': 'OSAI处于待命状态。告诉我你需要什么。',
    'ja-JP': 'OSAI準備完了。必要なことを教えてください。'
  }
};

class AIManager {
  private static instance: AIManager;
  private providers: AIProvider[] = [geminiProviderInstance, new LocalFallbackProvider()];
  private sessionMemory: MemoryEntry[] = [];
  private taskMemory: MemoryEntry[] = [];
  private readonly MAX_SESSION_MEMORY = 10;
  private readonly MAX_TASK_MEMORY = 15;

  private constructor() {}

  public static getInstance(): AIManager {
    if (!AIManager.instance) {
      AIManager.instance = new AIManager();
    }
    return AIManager.instance;
  }

  public getGreeting(lang: SupportedLanguage, profile: CognitiveProfile): string {
    return MODE_GREETINGS[profile][lang] || MODE_GREETINGS[profile]['pt-BR'];
  }

  public updateMemory(role: 'user' | 'ai' | 'system', content: string, scope: MemoryScope = MemoryScope.SESSION) {
    const entry: MemoryEntry = { role, content, timestamp: Date.now(), scope };
    
    if (scope === MemoryScope.SESSION) {
      this.sessionMemory.push(entry);
      if (this.sessionMemory.length > this.MAX_SESSION_MEMORY) this.sessionMemory.shift();
    } else {
      this.taskMemory.push(entry);
      if (this.taskMemory.length > this.MAX_TASK_MEMORY) this.taskMemory.shift();
    }
  }

  public async getSuggestion(params: Omit<AIRequestParams, 'sessionMemory' | 'taskMemory'>): Promise<Suggestion | null> {
    const fullParams: AIRequestParams = {
      ...params,
      sessionMemory: [...this.sessionMemory],
      taskMemory: [...this.taskMemory]
    };

    for (const provider of this.providers) {
      try {
        const suggestion = await provider.getSuggestion(fullParams);
        if (suggestion) {
          audit.log('SYSTEM', suggestion.riskLevel === 'HIGH' ? 'READY' : 'IDLE' as any, 
            `AI Suggestion generated by ${provider.name}`, { providerId: provider.id });
          
          // Determine memory scope: if it's an action, it belongs to the current Task
          const scope = suggestion.isSuggestion ? MemoryScope.TASK : MemoryScope.SESSION;
          this.updateMemory('user', params.context, scope);
          this.updateMemory('ai', suggestion.description, scope);
          
          return suggestion;
        }
      } catch (err) {
        console.warn(`Provider ${provider.id} failed, attempting next...`, err);
      }
    }

    audit.log('SYSTEM', 'ERROR' as any, 'All AI providers failed to generate a response.');
    return null;
  }

  /**
   * Clears the current task context. Called on completion or cancellation.
   */
  public clearTaskMemory() {
    audit.log('SYSTEM', 'IDLE' as any, 'Clearing task memory scope.');
    this.taskMemory = [];
  }

  /**
   * Clears the entire session context.
   */
  public purgeMemory() {
    audit.log('SYSTEM', 'IDLE' as any, 'Purging session and task memory.');
    this.sessionMemory = [];
    this.taskMemory = [];
  }
}

export const aiManager = AIManager.getInstance();
